### PR TITLE
upgrade to occ v1 which stops compiling to commonjs modules and starts publishing ecmascript modules instead

### PR DESCRIPTION
**Pull request by JakeChampion**
If it turns out to break anything, this is the plan of action:

    Revert the change
    Release a new version of origami-ci-tools
    Release a patch to every component that was released since this change went in
    Revert the change in occ

### CODE REVIEW

**Comment by notlee** [comment]
Would this change the default import?

**Comment by JakeChampion** [comment]
@notlee could you elaborate about what you mean, I don't understand, sorry

**Comment by notlee** [comment]
This is going to break for anyone using npm and commonjs require syntax?

```js
const Table = require("@financial-times/o-table");
```

>If it turns out to break anything, this is the plan of action:

Is the plan to hope that's a nonexistent usecase given how new our npm option is?

**Comment by JakeChampion** [comment]
pause this as it would trigger a major cascade

**Review by notlee — DISMISSED** [review]

**Comment by JakeChampion** [comment]
This work was done in https://github.com/Financial-Times/origami-ci-tools/commit/8554245d62ff5f888f8645b988323da4722fc52e and turned out to not be a breaking change

**Pull request closed without merging**
