### PR TITLE
 Breaking: Origami version 2 compatible version of origami-ci-tools

### PR DESCRIPTION
**Pull request by JakeChampion**
This is the main branch for the work required to make this project compatible with Origami version 2.

Work will be done in branches off of this branch (version-3).

### CODE REVIEW

**Comment by JakeChampion** [comment]
This is currently released as [v3.0.0-beta.2](https://github.com/Financial-Times/origami-ci-tools/releases/tag/v3.0.0-beta.2)

**Comment by notlee** [comment]
hey @Financial-Times/origami-core, ci-tools does less than it used:

On branch:
```
obt init
obt verify
obt test
```

On release:
- figures out if it's a prerelease or not
- `npm publish ...` accordingly

Since its doing less I don't think it's helping us keep our release flows consistent across components, but does add an extra step to updating them. I'm in favour of revisiting how we make it less of a pain to update all component workflows in the future (still holding out mono repo hopes) but for now think it would be a good idea to deprecate ci-tools in favour of handling pre-releases the same way we do for non-components:
- https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-latest.yml
- https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-prerelease.yml

Thoughts?

**Comment by JakeChampion** [comment]
> hey @Financial-Times/origami-core, ci-tools does less than it used:
> 
> On branch:
> 
> ```
> obt init
> obt verify
> obt test
> ```
> 
> On release:
> 
>     * figures out if it's a prerelease or not
> 
>     * `npm publish ...` accordingly
> 
> 
> Since its doing less I don't think it's helping us keep our release flows consistent across components, but does add an extra step to updating them. I'm in favour of revisiting how we make it less of a pain to update all component workflows in the future (still holding out mono repo hopes) but for now think it would be a good idea to deprecate ci-tools in favour of handling pre-releases the same way we do for non-components:
> 
>     * [https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-latest.yml](https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-latest.yml?rgh-link-date=2021-02-17T16%3A35%3A00Z)
> 
>     * [https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-prerelease.yml](https://github.com/Financial-Times/origami-build-tools/blob/master/.github/workflows/publish-to-npm-as-prerelease.yml?rgh-link-date=2021-02-17T16%3A35%3A00Z)
> 
> 
> Thoughts?

Yes, completely agree here, lets move it to a github workflow 👍

**Comment by notlee** [comment]
Closing as we're going to replace ci-tools with updated workflows for the reasons listed above, as done here for o-test-component: https://github.com/Financial-Times/o-test-component/pull/100

We will already be creating issues to upgrade components to spec v2 and I've made a note of this step for the checklist

**Pull request closed without merging**
