### PR TITLE
Make a special case for ftdomdelegate as it is not published under a namespace

### LINKED ISSUE #59: Use npm package name as tarball name when extracting
currently this project doesn't handle well when an npm package name is different than the repo name, because we try to extract a tarball with the name of the repo.
 can fix that by using the npm name instead of the repo name for the tarball extract command
example: https://github.com/Financial-Times/ftdomdelegate/pull/113/checks?check_run_id=712901661

### PR DESCRIPTION
**Pull request by JakeChampion**
Resolves #59

### CODE REVIEW

**Comment by chee** [comment]
actually, hmm. 
the origami component specification says, of the name: "This name must be used as the repository name" so origami-ci-tools wasn't doing anything wrong.

also ftdomdelegate's name in the package json IS ftdomdelegate? so i'm not sure what's going on

https://origami.ft.com/spec/v1/components/#naming-conventions

**Comment by chee** [comment]
let's cancel this piece of work, something else is going on in that repo

**Comment by JakeChampion** [comment]
The issue is that origami-ci-tools is assuming all packages will be namespaced under `@financial-times` whereas we special cased ftdomdelegate to not be namespaced -- 

https://github.com/Financial-Times/origami-component-converter/blob/1d710ad4b9dfda6895fd88b25313f5ec9c7b2f7d/lib/npm.js#L95-L104

**Comment by chee** [comment]
lol

**Comment by chee** [comment]
excellent!!!

**Review by chee — APPROVED** [review]
!!!!! excellent work

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v2.0.2 :tada:

**Pull request merged**
